department-for-transport-BODS/bods-backend

.github/workflows/cleanup-branches.yaml
.github/workflows/deploy.yml
.vscode/settings.json
VERSION
fares-etl.yaml
periodic-tasks.yaml
pyproject.toml
src/boilerplate/common_layer/database/models/error_codes.py
src/boilerplate/common_layer/exceptions/__init__.py
src/boilerplate/common_layer/exceptions/exceptions_download.py
src/timetables_etl.statemachine.json
src/timetables_etl/download_dataset/app/file_download.py
src/timetables_etl/generate_output_zip/app/generate_output_zip.py
src/timetables_etl/generate_output_zip/app/models/model_lambda.py
tests/timetables_etl/download_dataset/test_download_dataset.py
tests/timetables_etl/download_dataset/test_file_download.py
timetables-etl.yaml
tools/zip_tools/cli.py
tools/zip_tools/multi_zip_maker.py
tools/zip_tools/xml_formatter.py
tools/zip_tools/zip_repackage.py

- #441
- https://kpmgengineering.atlassian.net/browse/BODS-8699 
- #438 
- #437 
- #439

release(test): v1.0.133

---

VERSION

Bumping version to re-build dev after re-integrating hot fix from main

release(dev): v1.0.135

---

.github/workflows/build.yml
.github/workflows/deploy.yml

JIRA: https://kpmgengineering.atlassian.net/browse/BODS-8085

ci(DisableDev): Disable deployments to DEV temporarily 

---

VERSION
src/timetables_etl.statemachine.json
src/timetables_etl/exception_handler/app/exception_handler.py

Key Details:
- Add ObjectKey, DatasetRevisionId and DatasetType to all "Step Failed" logs
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-8719

fix(ExceptionHandler): Add missing data to exception handler log

---

VERSION

release(dev): v1.0.137

---

VERSION
src/common_lambdas/clamav_scanner/app/clamav_scanner.py
src/common_lambdas/clamav_scanner/app/models.py
src/timetables_etl.statemachine.json

The reprocessing step needs the anti virus scan to be skipped so `SkipVirusScan` has been added as a parameter with default False
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-7715

feat(ClamAV): Add Option to Skip ClamAV Step

---

VERSION
src/timetables_etl.statemachine.json

The reference to the variable was missing $
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-7715

fix(timetables-sm): Add $ to performETLOnly in ClamAV step

---

VERSION
src/timetables_etl.statemachine.json

Reverting breaking change to DQS trigger

fix(DQSTrigger): Revert change to trigger

---

.github/workflows/lint-pr.yaml
VERSION
fares-etl.yaml
src/boilerplate/common_layer/database/client.py
src/boilerplate/common_layer/database/repos/repo_fares.py
timetables-etl.yaml
tools/db_viewer/cli.py
tools/db_viewer/fares.py
tools/db_viewer/naptan.py
tools/db_viewer/organisation.py
tools/db_viewer/timetables.py

- #481 
- https://kpmgengineering.atlassian.net/browse/BODS-8866

release(test): v1.0.147

---

VERSION
src/fares_etl/etl/app/transform/metadata.py
src/fares_etl/metadata_aggregation/app/transform/transform_metadata.py

- Add list of stops that are extracted from the netex
- Add an error log if not all stops in the netex are found in the dynamodb cache
- Add log with metadata object count in aggregation step

refactor(netex-etl): add logging of naptan stop ids and their discrepancies

---

VERSION
src/boilerplate/common_layer/database/models/__init__.py
src/boilerplate/common_layer/database/models/model_junction.py
src/boilerplate/common_layer/database/repos/__init__.py
src/boilerplate/common_layer/database/repos/repo_junction.py
src/timetables_etl/generate_output_zip/app/generate_output_zip.py

- #492 
- https://kpmgengineering.atlassian.net/browse/BODS-8897

release(test): v1.0.153

---

VERSION
periodic-tasks.yaml
src/boilerplate/common_layer/xml/netex/parser/netex_publication_delivery.py
src/boilerplate/common_layer/xml/utils/__init__.py
src/boilerplate/common_layer/xml/utils/xml_duration.py
src/timetables_etl/etl/app/transform/service_pattern_stops_durations.py
tests/timetables_etl/etl/transform/test_service_pattern_stops_time.py
tests/xml/utils/test_xml_duration.py
tools/file_viewer/txc/tabs/journey_pattern_sections/tab_jps.py
tools/file_viewer/txc/tabs/vehicle_journeys/tab_vehicle_journeys.py

Key Changes:
- https://github.com/department-for-transport-BODS/bods-backend/pull/497
- https://kpmgengineering.atlassian.net/browse/BODS-8930
- https://github.com/department-for-transport-BODS/bods-backend/pull/498
- https://kpmgengineering.atlassian.net/browse/BODS-8934

release(test): v1.0.155

---

VERSION
src/boilerplate/common_layer/exceptions/exceptions_fares.py
src/fares_etl/metadata_aggregation/app/metadata_aggregation.py
src/fares_etl/validation/app/fares_validator.py
src/fares_etl/validation/app/schema/schema.json
src/fares_etl/validation/app/types.py

[fix: handle schema violation error message](https://github.com/department-for-transport-BODS/bods-backend/pull/507)

release(test): v1.0.157

---

VERSION
src/timetables_etl/etl/app/load/servicepatterns_distance.py
tests/timetables_etl/etl/load/test_servicepatterns_distance.py

Key changes:
- https://github.com/department-for-transport-BODS/bods-backend/pull/543
- https://kpmgengineering.atlassian.net/browse/BODS-9210

release(test): v1.0.169

---

VERSION
src/timetables_etl/generate_output_zip/app/generate_output_zip.py
src/timetables_etl/generate_output_zip/app/output_processing.py

Key changes:
- https://github.com/department-for-transport-BODS/bods-backend/pull/536
- https://kpmgengineering.atlassian.net/browse/BODS-8995

release(test): v1.0.171

---

VERSION
src/timetables_etl/download_dataset/app/download_dataset.py

No Space left on device error was received at the time of 4PM job,
We have implemented the cleanup code to remove downloaded file from temp dir
Key Details:
Remove downloaded dataset from temp folder once it is uploaded on S3
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-9252

release(test): v1.0.173

---

VERSION
periodic-tasks.yaml
poetry.lock
pyproject.toml
src/boilerplate/common_layer/database/models/model_transmodel.py
src/boilerplate/common_layer/database/repos/repo_common.py
src/boilerplate/common_layer/database/repos/repo_junction.py
src/boilerplate/common_layer/database/repos/repo_transmodel.py
src/periodic_tasks/consolidate_tracks/app/handler_consolidate_tracks.py
src/periodic_tasks/consolidate_tracks/app/utils.py
tests/boilerplate/common_layer/database/repos/test_repo_common.py
tests/boilerplate/common_layer/database/repos/test_repo_junction.py
tests/boilerplate/common_layer/database/repos/test_repo_naptan.py
tests/boilerplate/common_layer/database/repos/test_repo_transmodel.py
tests/factories/database/__init__.py
tests/factories/database/junction.py
tests/factories/database/transmodel.py
tests/periodic_tasks/consolidate_tracks/test_consolidate_tracks.py
tests/periodic_tasks/consolidate_tracks/test_utils.py

Key changes:
- https://github.com/department-for-transport-BODS/bods-backend/pull/531
- https://kpmgengineering.atlassian.net/browse/BODS-9077

release(test): v1.0.174

---

VERSION
src/boilerplate/common_layer/database/repos/repo_transmodel.py
src/periodic_tasks/consolidate_tracks/app/handler_consolidate_tracks.py
tests/boilerplate/common_layer/database/repos/test_repo_transmodel.py
tests/periodic_tasks/consolidate_tracks/test_consolidate_tracks.py

Key Changes:
- https://github.com/department-for-transport-BODS/bods-backend/pull/574
- https://kpmgengineering.atlassian.net/browse/BODS-9077

release(test): v1.0.180

---

VERSION
src/boilerplate/common_layer/database/repos/repo_transmodel.py
src/periodic_tasks/consolidate_tracks/app/handler_consolidate_tracks.py
src/timetables_etl/generate_output_zip/app/generate_output_zip.py

Use CTE for geometry transformation in query that finds out similar pair of tracks for stop point pair
Reduce batch size to 500 so that lambda does not timeout
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-9475

fix(ConsolidateTracks): Modify query to use CTE and reduce batch size

---

VERSION
periodic-tasks.yaml

Key Changes:
- https://github.com/department-for-transport-BODS/bods-backend/pull/602

release(test): v1.0.186

---

VERSION
src/boilerplate/common_layer/utils_location.py
src/boilerplate/common_layer/xml/txc/parser/route_sections.py
tests/xml/txc/parser/txc_route_section/test_txc_route_section_location.py

Key Details:
- Implement parsing and transformation of Easting/Northing coordinates in Tracks data
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-9237

fix(ETLProcess): Add parsing for easting and northing coordinates for Tracks

---

VERSION
src/boilerplate/common_layer/utils_location.py
src/boilerplate/common_layer/xml/txc/parser/route_sections.py
tests/xml/txc/parser/txc_route_section/test_txc_route_section_location.py

Revert Add parsing for easting and northing coordinates for Tracks (#622)
Revert PR
https://github.com/department-for-transport-BODS/bods-backend/pull/547 changes due to import issues
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-9237

release(test): v1.0.190

---

VERSION
poetry.lock
pyproject.toml
src/boilerplate/common_layer/utils_location.py
src/boilerplate/common_layer/xml/txc/parser/route_sections.py
tests/xml/txc/parser/txc_route_section/test_txc_route_section_location.py

Eastings/northings routes are not parsed in the code, when uploaded a TXC file with Eastings/northings route, tracks data is not seen in test DB
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-9237

fix(ETLProcess): Fix build issues with pyproj (#645)
