VERSION, src/timetables_etl.statemachine.json, src/timetables_etl/exception_handler/app/exception_handler.py, src/timetables_etl/exception_handler/app/models.py, tests/timetables_etl/exception_handler/test_exception_handler.py
Key Details:
- Add StepName input parameter to exception handler
- Log the failed step + populate task_name_failed field in the DatasetETLTaskResult
- Add FailDatasetRevision and FailDatasetETLTaskResult input parameters to exception handler
- Adds control for whether or not to fail the DatasetRevision and the DatasetETLTaskResult
- Add catch block to DQS Trigger to mark only the DatasetETLTaskResult as failed, not the DatasetRevision (matches existing bods celery behaviour)
- Add exception handler to file-level processing steps for consistent logging (without failing task result or revision)
Here is an example of how we can use this to filter failures in datadog by step:
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-8719
=> fix(ExceptionHandler): Exception handling improvements

src/timetables_etl/download_dataset/app/download_dataset.py, tests/timetables_etl/download_dataset/test_download_dataset.py, timetables-etl.yaml
Key Details:
- Right now we're just using the filename from the end of the `revision.url_link`, which is not unique (for example http://test.com/current.zip and http://other-url.com/current.zip would produce the same remote filename which is then uploaded to S3
- In this PR we add the `dataset_id`, `revision_id` and current datetime to the remote file name (S3 object key) to avoid collisions/overwrites
- Increase memory allocation for DownloadDataset lambda to avoid OOM exceptions
https://kpmgengineering.atlassian.net/browse/BODS-8750
=> fix(DownloadDataset): Make remote filename for S3 unique when downloading from URL + increase memory allocation

fares-etl.yaml, src/fares_etl.statemachine.json
In this PR:
- Implement the same semaphore logic in Fares that we have in Timetables. Aside from the additional functionality, this also fixes validation issues we were seeing executing the `GenerateOutputZip` (by adding missing input params; `DatasetType` and `lockacquiredtime`)
- Fix input parameters for exception handler + add exception handler to file-level processing for consistent logging purposes
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-8773
=> fix(Fares): Implement semaphores

VERSION, src/fares_etl.statemachine.json
We noticed that the `DatasetETLTaskResultId` input was missing, which would cause the state machine to create a new one itself (which is only intended for testing in isolation; usually Django is responsible for creating the task result)
=> fix(Fares): Fix fares initialize pipeline payload

VERSION, src/timetables_etl.statemachine.json
Intentionally introducing a breaking change to the DQS trigger so that the exception handling can be tested. Once we've tested the exception handling this change will be reverted
=> chore(test): DQS Trigger

VERSION, src/timetables_etl.statemachine.json
In the state machine input payload if `performETLOnly` is `true` then only the File Attributes and ETL Process lambdas will be executed
Skipping:
- ClamAV Scan
- File Validation
- Schema and Post Schema Check
- PTI
- DQS Trigger
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-7715
=> feat(timetables-etl): Use performETLOnly variable to skip Schema Checks and PTI

VERSION, src/timetables_etl.statemachine.json
Fix for:
> States in the child workflow of a Distributed Map State can only reference variables assigned in that child workflow.
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-7715
=> fix(timetables-sm): Remap the StateMachine Variables

src/boilerplate/common_layer/xml/txc/parser/services_flexible.py, src/boilerplate/common_layer/xml/txc/parser/stop_points/parse_stop_point_types.py
- Use parse_jp_direction to return a JourneyPatternVehicleDirectionT type instead
- Remove unnecessary cast when parsing BayStructures
=> refactor(txc-parser): Fix linting issues

src/boilerplate/common_layer/database/dataclasses/__init__.py, src/boilerplate/common_layer/database/dataclasses/stats.py, src/boilerplate/common_layer/database/repos/repo_organisation.py, src/boilerplate/common_layer/database/repos/repo_transmodel.py, src/boilerplate/common_layer/database/repos/utils.py, src/timetables_etl/generate_output_zip/app/etl_revision_stats.py, src/timetables_etl/generate_output_zip/app/generate_output_zip.py, tests/boilerplate/common_layer/database/repos/test_repo_organization.py, tests/boilerplate/common_layer/database/repos/test_repo_transmodel.py
In this PR we add some code to the Generate Output Zip step to:
- Build a set of stats based on all services/txc file attributes processed during the ETL step
- Update the revision fields with those stats (`publisher_creation_datetime`, `publisher_modified_datetime`, `first_expiring_service`, `last_expiring_service`, `first_service_start`)
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-8759
=> fix(GenerateOutputZip): Populate missing revision metadata fields

VERSION, fares-etl.yaml, timetables-etl.yaml
The exception handler and intialize pipeline have ran into out of memory erorrs with their default 256mb.
- Increase default lambda memory to 384
- Increase File Attributes ETL memory from 768 to 1024
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-8866
=> fix(sam): Increase lambda memory to avoid Out of Memory crashes

VERSION, src/boilerplate/common_layer/db/constants.py, src/boilerplate/common_layer/xml/netex/helpers/__init__.py, src/boilerplate/common_layer/xml/netex/helpers/helpers_fare_frame_fare_products.py, src/boilerplate/common_layer/xml/netex/helpers/helpers_fare_frame_tariff.py, src/boilerplate/common_layer/xml/netex/helpers/helpers_fare_frame_zones.py, src/boilerplate/common_layer/xml/netex/helpers/helpers_resource_frame.py, src/boilerplate/common_layer/xml/netex/helpers/helpers_service_frame.py, src/fares_etl/etl/app/etl_process.py, src/fares_etl/etl/app/load/metadata.py, src/fares_etl/etl/app/transform/data_catalogue.py, src/fares_etl/etl/app/transform/metadata.py, src/fares_etl/metadata_aggregation/app/load/dataset.py, src/fares_etl/metadata_aggregation/app/load/metadata.py, src/fares_etl/metadata_aggregation/app/load/violations.py, src/fares_etl/metadata_aggregation/app/metadata_aggregation.py, src/fares_etl/metadata_aggregation/app/transform/transform_metadata.py
Some discrepancies have been found with the existing setup, so this change adds extra logging
- Add FARES_ETL_PROCESS step name to differentiate from timetables
- Add file_processing_result_to_db decorator to FARES_METADATA_AGGREGATION
- Add netex helper functions to module's `__init__.py` to tidy up imports
=> refactor(fares): add extra logs to the fares lambdas

VERSION, src/boilerplate/common_layer/xml/netex/parser/netex_utility.py, tests/fares_etl/etl/transform/test_metadata.py, tests/xml/netex/conftest.py, tests/xml/netex/fare_frame/test_netex_fare_tariff.py, tests/xml/netex/test_netex_utility.py, tests/xml/netex/test_scheduled_stop_point_ref.py
Some netex files omit the Z or timezone identifier (+0000) so we can only assume it's in UTC
This may fix some comparison issues as this should ensure that all timezones in the parsed netex data are not naive
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-8833
=> fix(netex-parser): Parse timestamps without timezone as UTC

VERSION, src/fares_etl/metadata_aggregation/app/metadata_aggregation.py, src/fares_etl/metadata_aggregation/app/transform/transform_metadata.py, tests/fares_etl/metadata_aggregation/transform/test_transform_metadata.py
It turns out that that duplicates are being counted but we should be able to calculate the unique items using the FaresDataCatalogueMetadata object that populates the fares_datacataloguemetadata table in the ETL process
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-8832
=> fix(fares-aggregation): Calculate unique counts for User Profiles, Trip and Pass products

VERSION, src/boilerplate/common_layer/xml/netex/parser/netex_utility.py, tests/xml/netex/test_netex_utility.py
Bods is configured to use Europe/London as the timezone when adding items into the DB
This means that dates without timezones will need to parsed as Europe/London to correctly have the right date in them.
- Default missing timezones to Europe/London using ZoneInfo
- Add test cases for BST (hour shift) and GMT
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-8833
=> fix(netex-parser): assume Europe/London instead of UTC for timestamps without Timezone

VERSION, src/boilerplate/common_layer/xml/netex/parser/netex_publication_delivery.py, src/boilerplate/common_layer/xml/utils/__init__.py, src/boilerplate/common_layer/xml/utils/xml_duration.py, src/timetables_etl/etl/app/transform/service_pattern_stops_durations.py, tests/timetables_etl/etl/transform/test_service_pattern_stops_time.py, tests/xml/utils/test_xml_duration.py, tools/file_viewer/txc/tabs/journey_pattern_sections/tab_jps.py, tools/file_viewer/txc/tabs/vehicle_journeys/tab_vehicle_journeys.py
The value in that section of the Netex document is not parsable as a timedelta but instead requires parsing as an ISO duration
- Move parse_duration into shared xml utils
- Update with test cases for negative durations and days
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-8930
=> fix(netex-parser): Parse PublicationRefreshInterval as ISO 8601 duration

VERSION, src/timetables_etl/download_dataset/app/download_dataset.py
No Space left on device error was received at the time of 4PM job,
We have implemented the cleanup code to remove downloaded file from temp dir
Key Details:
- Remove downloaded dataset from temp folder once it is uploaded on S3
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-9252
=> fix(ETLProcess): Cleanup once remote dataset  file is move to s3

VERSION, src/timetables_etl/generate_output_zip/app/output_processing.py
Updated comparison logic in order to rectify the comparison of files, 
Although we have very few such instances, but still we can make if work for those few. 
From the original zip file (downloaded from s3) get the list of files and split the path with /, consider the last part as file name.
Key Details:
- From the original zip file (downloaded from s3) get the list of files and split the path with /, consider the last part as file name.
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-9370
=> fix(ETLProcess): Resolved 1 level folder issue for zip file creation

VERSION, src/timetables_etl/generate_output_zip/app/output_processing.py
Error message in the exception caused problem while creating a task error record
Trimmed the message and replaced file names with total number of missing files
Key Details:
- Trimmed the message from generate output lambda and replaced file names with total number of missing files
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-9370
=> release(test): Trimmed error message (#579)

VERSION, src/timetables_etl/generate_output_zip/app/generate_output_zip.py
Currently when there are no successful files in the dataset, an empty zip file is created. Added a condition before building a new zip file to check if there are any successful files otherwise skip the creation of zip file and don't update the `modified_file_hash`
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-9456
=> fix(GenerateOutput): Skip zip file creation if there are no successful files

VERSION, src/boilerplate/common_layer/database/repos/repo_transmodel.py, src/periodic_tasks/consolidate_tracks/app/handler_consolidate_tracks.py
… (#590)
- Use CTE for geometry transformation in query that finds out similar pair of tracks for stop point pair
- Reduce batch size to 500 so that lambda does not timeout
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-9475
=> release(Test): v1.0.184 Consolidate tracks into test

VERSION, periodic-tasks.yaml
…(#607)
Consolidate-tracks state machine schedule updated from 02:00 UTC to 00:30 UTC to avoid overlap with 4am (BST) generate timetable job.
JIRA: https://kpmgengineering.atlassian.net/browse/BODS-9550
=> release(test): v1.0.187
